name: "\U0001F41B UI Bug Report"
description: "Report a visual bug or issue in the production application"
labels: ["Bug: UI", "needs review"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file an UI bug report! Please fill out this entire form. The most important piece are screenshots/videos/steps that led to the bug.
  - type: input
    attributes:
      label: What device did this occur on?
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Android is your device running?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Have you modified your device's display or font size?
      multiple: false
      options:
        - "Yes"
        - "No"
        - I don't know
      description: |
        This helps determine if the issue stems from the user modifying the system UI.
        Essentially, see if you ever modified a value in: `Settings > Display > Display size and text`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Summary
      description: |
        Clearly describe the problem or steps that led to this problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot / Video
      description: |
        A screenshot of the UI issue. A video replicating this issue would be very helpful.
    validations:
      required: true
