name: "🙋 Feature Request"
description: "Want us to add something to Music?"
labels: ["invalid issue: feature request"]
body:
  - type: markdown
    attributes:
      value: Thanks for helping us make Music even better! 😀 Unfortunately, this is not the right place for feature requests. Please find a discussion about your request (or create a new one) in the [Discussions Tab](https://github.com/MissingCore/Music/discussions) instead.
  - type: dropdown
    attributes:
      label: Do you understand that any feature requests opened will be closed?
      options:
        - "Yes"
    validations:
      required: true
