name: Issue Triage
on:
  issues:
    types: [labeled]

jobs:
  question:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.label.name, 'invalid issue: question') }}"
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Hello! Our GitHub issues are reserved for bug reports.

              If you have a question about Music, please find a discussion about your request (or create a new one) in the [Discussions Tab](https://github.com/MissingCore/Music/discussions) instead.
            `})
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            })

  feature-request:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.label.name, 'invalid issue: feature request') }}"
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Hello! Our GitHub issues are reserved for bug reports.

              If you would like to request a feature, please find a discussion about your request (or create a new one) in the [Discussions Tab](https://github.com/MissingCore/Music/discussions) instead.
            `})
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            })
