name: Create `latest-stable` Branch
on:
  workflow_dispatch:

jobs:
  create-latest-stable-branch:
    name: Create `latest-stable` branch from latest stable release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Ensure we have a link to the original repository
        run: |
          git remote add upstream https://github.com/MissingCore/Music.git
          git remote -v

      - name: Get latest tag and create a `latest-stable` branch from it
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(gh release list --repo MissingCore/Music --exclude-pre-releases --limit 1 --json tagName --jq '.[0].tagName')
          echo "Latest Tag: $LATEST_TAG"
          git fetch --no-tags upstream tag $LATEST_TAG
          git checkout -b latest-stable $LATEST_TAG
          git push -u -f origin latest-stable
